### ISSUE TITLE
Android version?

### ISSUE THREAD

**Issue by ScottRFrost** [benoitvallon/react-native-nw-react-calculator#2]
Any samples of how to do this as an Android app?

I need to support both (especially since Android sells 5 devices per 1 sold by Apple).

**Comment by dsibiski** [comment]
Already working on it here: https://github.com/benoitvallon/react-native-nw-react-calculator/pull/1

:smiley:

**Comment by ColCh** [comment]
It will be nice to see Android example as well as isomorphic version (aka universal JavaScript)

**Comment by benoitvallon** [comment]
@ColCh a universal javascript version was in the list of things that I would have liked to do in this project although I think it will not be a very good example because this project is really simple (doesn't really involve routes for example).

But if you still would like to see it, please create an other issue as this one was specific to android.

Thank you
